version: '2'
services:
  app:
    build: .
    command: npm run actors
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://anypay@postgres/auction
      AMQP_URL: amqp://guest:guest@auction.anypay.global:5566/
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: anypay
      POSTGRES_DB: auction

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: anypay
      RABBITMQ_DEFAULT_PASS: auction
