version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          DATABASE_URL: postgres://postgres:@localhost:5432/anypay_auction
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: anypay_auction

    steps:
      - run:
      name: Waiting for Postgres to be ready
      command: |
        for i in `seq 1 10`;
        do
          nc -z localhost 5432 && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo Failed waiting for Postgres && exit 1
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay/auction .
      - run:
          name: Run Tests
          command: docker run -it -e DATABASE_URL=$DATABASE_URL anypay/auction npm test
      - add_ssh_keys
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker.sh
            ssh -oStrictHostKeyChecking chef@auction.anypay.global "sudo /opt/anypay/deploy_auction.sh"

  deploy_staging:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t anypay/auction .
      - run:
          name: Deploy To Server
          command: |
            ./push_to_docker.sh
            ssh -oStrictHostKeyChecking=no chef@auction.anypay.global "sudo /opt/anypay/deploy_auction.sh"

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  build-and-deploy-staging:
      jobs:
        - build
        - deploy_staging:
            requires:
              - build
            filters:
              branches:
                only: staging
